version: "3"

services:
  db:
    container_name: postgres_db
    image: postgres:14.2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql
    ports:
      - "5432:5432"

  calendar:
    container_name: calendar
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db